FROM python:3.11-slim

WORKDIR /app

COPY app ./app

ENV ROUTER_MODE=conservative \
    LOCAL_CONFIDENCE_THRESHOLD=1.0 \
    FIREWORKS_MAX_TOKENS=256 \
    ROUTER_PROMPT_POLICY_REMOTE_ACCURACY=original \
    ROUTER_PROMPT_POLICY_REMOTE_CODE=original \
    ROUTER_PROMPT_POLICY_REMOTE_FORMAT_STRICT=original \
    ROUTER_PROMPT_POLICY_REMOTE_CONCISE=original

CMD ["python", "-m", "app.main"]
